apiVersion: v1
kind: Secret
metadata:
  name: dyson-devices
  namespace: dyson-graph
type: Opaque
stringData:
  cloudflare_creds.ini: |
    [cloudflare_creds]
    email = youremail@something.com
    auth_key = ldk987jkhgklh99s80somethingheref078zcv
  dns.ini: |
    [yourdomain.com]
    records = ["subdomain_to_update", "second_thing_to_update"]

    [yourotherdomain.org]
    records = ["more_domain_to_update"]

